# Generated by Django 2.1.7 on 2019-03-02 05:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='评论唯一标识符')),
                ('msg_ID', models.IntegerField(verbose_name='所评论信息唯一标识符')),
                ('user_ID', models.IntegerField(verbose_name='评论用户唯一标识符')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('img', models.ImageField(upload_to='command_img', verbose_name='评论图片')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('msg_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='信息唯一标识符')),
                ('pos_x', models.IntegerField()),
                ('pox_y', models.IntegerField()),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('img', models.TextField(verbose_name='照片名')),
                ('author', models.IntegerField(verbose_name='作者')),
                ('like', models.IntegerField(verbose_name='点赞数')),
                ('dislike', models.IntegerField(verbose_name='点踩数')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('comments', models.TextField(verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('unique_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='用户唯一标识符')),
                ('user_ID', models.CharField(max_length=32, verbose_name='用户ID')),
                ('user_name', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('avatar_name', models.ImageField(upload_to='avatars', verbose_name='头像存储名')),
                ('follows', models.TextField(verbose_name='关注用户')),
                ('fans', models.TextField(verbose_name='粉丝')),
                ('msgs', models.TextField(verbose_name='所发推文')),
                ('friends', models.TextField(verbose_name='好友')),
                ('introductino', models.TextField(verbose_name='简介')),
            ],
        ),
    ]
