# Generated by Django 2.1.7 on 2019-03-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fans',
            field=models.TextField(default='[]', verbose_name='粉丝'),
        ),
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.TextField(default='[]', verbose_name='关注用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.TextField(default='[]', verbose_name='好友'),
        ),
        migrations.AlterField(
            model_name='user',
            name='introductino',
            field=models.TextField(default='', verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='msgs',
            field=models.TextField(default='[]', verbose_name='所发推文'),
        ),
    ]
