# Generated by Django 2.1.7 on 2019-03-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0002_auto_20190302_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_ID',
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='comment',
            name='who_dislike',
            field=models.TextField(default='[]', verbose_name='点踩用户'),
        ),
        migrations.AddField(
            model_name='message',
            name='who_dislike',
            field=models.TextField(default='[]', verbose_name='点踩用户'),
        ),
        migrations.AddField(
            model_name='message',
            name='who_like',
            field=models.TextField(default='[]', verbose_name='点赞用户'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=32, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='Content', verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='msg_ID',
            field=models.IntegerField(default=0, verbose_name='所评论信息唯一标识符'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_ID',
            field=models.IntegerField(default=0, verbose_name='评论用户唯一标识符'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.IntegerField(default=0, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='message',
            name='comments',
            field=models.TextField(default='[]', verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default='Content', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='message',
            name='dislike',
            field=models.IntegerField(default=0, verbose_name='点踩数'),
        ),
        migrations.AlterField(
            model_name='message',
            name='img',
            field=models.TextField(default='Pic', verbose_name='照片名'),
        ),
        migrations.AlterField(
            model_name='message',
            name='like',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='message',
            name='pos_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='pox_y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(default='Title', max_length=64, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_name',
            field=models.ImageField(default='rua.jpg', upload_to='avatars', verbose_name='头像存储名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='introductino',
            field=models.TextField(default='Hello, World', verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='000000', max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='user', max_length=32, verbose_name='用户名'),
        ),
    ]
