# Generated by Django 2.1.7 on 2019-03-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0002_auto_20190302_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_ID',
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='comment',
            name='who_dislike',
            field=models.TextField(default='[]', verbose_name='点踩用户'),
        ),
        migrations.AddField(
            model_name='message',
            name='who_dislike',
            field=models.TextField(default='[]', verbose_name='点踩用户'),
        ),
        migrations.AddField(
            model_name='message',
            name='who_like',
            field=models.TextField(default='[]', verbose_name='点赞用户'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=123, max_length=32, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='dislike',
            field=models.IntegerField(default=0, verbose_name='点踩数'),
        ),
        migrations.AlterField(
            model_name='message',
            name='like',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='message',
            name='pos_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='pox_y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='introductino',
            field=models.TextField(default='Hello, World', verbose_name='简介'),
        ),
    ]
