# Generated by Django 2.1.7 on 2019-03-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0004_auto_20190305_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='pox_y',
            new_name='pos_y',
        ),
    ]
