# Generated by Django 2.1.7 on 2019-07-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0006_auto_20190306_1340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
