# Generated by Django 2.1.7 on 2019-07-12 16:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WW', '0007_auto_20190713_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论唯一标识符')),
                ('content', models.TextField(default='Hello', verbose_name='评论内容')),
                ('like', models.IntegerField(default=0, verbose_name='点赞数')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论图片唯一标识符')),
                ('img', models.ImageField(upload_to='pic', verbose_name='存储图片')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW.Comment', verbose_name='该图片所属评论')),
            ],
            options={
                'verbose_name': 'CommentImage',
                'verbose_name_plural': 'CommentImages',
            },
        ),
        migrations.CreateModel(
            name='Followship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='开始关注的日期')),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='成为好友的日期')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='信息唯一标识符')),
                ('pos_x', models.FloatField(default=0, verbose_name='信息位置经度')),
                ('pos_y', models.FloatField(default=0, verbose_name='信息位置纬度')),
                ('title', models.CharField(max_length=62, verbose_name='信息标题')),
                ('content', models.TextField(verbose_name='信息内容')),
                ('like', models.IntegerField(default=0, verbose_name='点赞数')),
                ('dislike', models.IntegerField(default=0, verbose_name='点踩数')),
                ('add_date', models.DateField(default=django.utils.timezone.now, verbose_name='发布日期')),
                ('mod_date', models.DateField(auto_now=True, verbose_name='最后修改日期')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='MessageImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='信息图片唯一标识符')),
                ('img', models.ImageField(upload_to='pic', verbose_name='存储图片')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW.Message', verbose_name='该图片所属信息')),
            ],
            options={
                'verbose_name': 'MessageImage',
                'verbose_name_plural': 'MessageImages',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户唯一标识符')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('username', models.CharField(default='WWer', max_length=62, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('avatar', models.ImageField(default='rua.jpg', upload_to='avatars', verbose_name='头像')),
                ('introduction', models.TextField(default='Hello，World', verbose_name='简介')),
                ('follows', models.ManyToManyField(related_name='follow_set', through='WW.Followship', to='WW.User', verbose_name='关注用户')),
                ('friends', models.ManyToManyField(related_name='friend_set', through='WW.Friendship', to='WW.User', verbose_name='好友')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_author_set', to='WW.User', verbose_name='该信息作者'),
        ),
        migrations.AddField(
            model_name='message',
            name='who_dislike',
            field=models.ManyToManyField(related_name='message_who_dislike_set', to='WW.User', verbose_name='点踩该信息的用户'),
        ),
        migrations.AddField(
            model_name='message',
            name='who_like',
            field=models.ManyToManyField(related_name='message_who_like_set', to='WW.User', verbose_name='点赞该信息的用户'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiator_set', to='WW.User', verbose_name='发起申请的用户'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_set', to='WW.User', verbose_name='接受申请的用户'),
        ),
        migrations.AddField(
            model_name='followship',
            name='fan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_set', to='WW.User', verbose_name='粉丝'),
        ),
        migrations.AddField(
            model_name='followship',
            name='followed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_user_set', to='WW.User', verbose_name='被关注者'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comment_author_set', to='WW.User', verbose_name='该评论所属用户'),
        ),
        migrations.AddField(
            model_name='comment',
            name='msg',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='WW.Message', verbose_name='该评论所属信息'),
        ),
        migrations.AddField(
            model_name='comment',
            name='who_like',
            field=models.ManyToManyField(related_name='comment_who_like_set', to='WW.User', verbose_name='点赞该评论的用户'),
        ),
    ]
