# Generated by Django 2.1.7 on 2019-07-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0008_auto_20190713_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='who_like',
            field=models.ManyToManyField(blank=True, related_name='comment_who_like_set', to='WW.User', verbose_name='点赞该评论的用户'),
        ),
        migrations.AlterField(
            model_name='message',
            name='who_dislike',
            field=models.ManyToManyField(blank=True, related_name='message_who_dislike_set', to='WW.User', verbose_name='点踩该信息的用户'),
        ),
        migrations.AlterField(
            model_name='message',
            name='who_like',
            field=models.ManyToManyField(blank=True, related_name='message_who_like_set', to='WW.User', verbose_name='点赞该信息的用户'),
        ),
    ]
