# Generated by Django 2.1.7 on 2020-03-05 17:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0011_auto_20200227_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='图片唯一标识符')),
                ('img', models.ImageField(upload_to='pic', verbose_name='存储图片')),
                ('type', models.CharField(choices=[('universal', 'Universal'), ('avatar', 'Avatar')], default='universal', max_length=31, verbose_name='图片类型')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('size', models.FloatField(verbose_name='图片大小，单位为Mb')),
            ],
        ),
        migrations.AddField(
            model_name='commentimage',
            name='thumbnail',
            field=models.CharField(default='avatars/rua.jpg', max_length=500, verbose_name='存储缩略图片地址'),
        ),
        migrations.AddField(
            model_name='messageimage',
            name='thumbnail',
            field=models.CharField(default='avatars/rua.jpg', max_length=500, verbose_name='存储缩略图片地址'),
        ),
        migrations.AlterField(
            model_name='commentimage',
            name='img',
            field=models.CharField(default='avatars/rua.jpg', max_length=500, verbose_name='存储图片地址'),
        ),
        migrations.AlterField(
            model_name='messageimage',
            name='img',
            field=models.CharField(default='avatars/rua.jpg', max_length=500, verbose_name='存储图片地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_avatar_set', to='WW.Image', verbose_name='该用户头像'),
        ),
    ]
