# Generated by Django 2.1.7 on 2020-03-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0012_auto_20200306_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('avatar', 'Avatar'), ('universal', 'Universal')], default='universal', max_length=31, verbose_name='图片类型'),
        ),
    ]
