# Generated by Django 2.1.7 on 2020-03-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0015_auto_20200306_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('universal', 'Universal'), ('avatar', 'Avatar')], default='universal', max_length=31, verbose_name='图片类型'),
        ),
    ]
