# Generated by Django 2.1.7 on 2020-03-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0016_auto_20200306_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='size',
            field=models.FloatField(null=True, verbose_name='图片大小，单位为Mb'),
        ),
    ]
