# Generated by Django 2.1.7 on 2020-03-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0017_auto_20200306_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('avatar', 'Avatar'), ('universal', 'Universal')], default='universal', max_length=31, verbose_name='图片类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(default='Hello, World', verbose_name='简介'),
        ),
    ]
