# Generated by Django 2.1.7 on 2020-03-31 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0022_auto_20200326_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(1980, 1, 1, 0, 0), verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='unknown', max_length=31, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('universal', 'Universal'), ('avatar', 'Avatar')], default='universal', max_length=31, verbose_name='图片类型'),
        ),
    ]
