# Generated by Django 2.1.4 on 2020-03-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0025_auto_20200331_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='unknown', max_length=31, verbose_name='性别'),
        ),
    ]
