# Generated by Django 2.1.4 on 2020-03-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0026_auto_20200331_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('avatar', 'Avatar'), ('unknown', 'Unknown'), ('universal', 'Universal')], default='universal', max_length=31, verbose_name='图片类型'),
        ),
    ]
