# Generated by Django 2.1.4 on 2020-04-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0027_auto_20200331_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('avatar', 'Avatar'), ('universal', 'Universal'), ('unknown', 'Unknown')], default='universal', max_length=31, verbose_name='图片类型'),
        ),
    ]
