# Generated by Django 2.1.7 on 2020-04-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0028_auto_20200402_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='标签唯一标识符')),
                ('tag', models.TextField(max_length=62, verbose_name='标签')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('avatar', 'Avatar'), ('universal', 'Universal')], default='universal', max_length=31, verbose_name='图片类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='unknown', max_length=31, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='message',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='message_tag_set', to='WW.Tag', verbose_name='该信息的tag'),
        ),
    ]
