# Generated by Django 2.1.7 on 2020-04-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0030_auto_20200407_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('avatar', 'Avatar'), ('universal', 'Universal'), ('unknown', 'Unknown')], default='universal', max_length=31, verbose_name='图片类型'),
        ),
    ]
