# Generated by Django 2.1.7 on 2020-04-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0032_auto_20200409_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('child', 'Child'), ('parent', 'Parent')], default='parent', max_length=31, verbose_name='类型'),
        ),
    ]
