# Generated by Django 2.1.4 on 2020-04-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0034_auto_20200409_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('universal', 'Universal'), ('avatar', 'Avatar')], default='universal', max_length=31, verbose_name='图片类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='unknown', max_length=31, verbose_name='性别'),
        ),
    ]
