# Generated by Django 2.1.7 on 2020-04-09 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0035_auto_20200409_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='图片唯一标识符')),
                ('video', models.FileField(upload_to='video', verbose_name='存储视频')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('size', models.FloatField(null=True, verbose_name='图片大小，单位为Mb')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('child', 'Child'), ('parent', 'Parent')], default='parent', max_length=31, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='who_like',
            field=models.ManyToManyField(blank=True, related_name='comment_who_like_set', to='WW.User', verbose_name='点赞该评论的用户'),
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('universal', 'Universal'), ('unknown', 'Unknown'), ('avatar', 'Avatar')], default='universal', max_length=31, verbose_name='图片类型'),
        ),
        migrations.AlterField(
            model_name='message',
            name='mention',
            field=models.ManyToManyField(blank=True, related_name='message_mention_user', to='WW.User', verbose_name='被该信息@的用户'),
        ),
        migrations.AlterField(
            model_name='message',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='message_tag_set', to='WW.Tag', verbose_name='该信息的tag'),
        ),
        migrations.AlterField(
            model_name='message',
            name='who_dislike',
            field=models.ManyToManyField(blank=True, related_name='message_who_dislike_set', to='WW.User', verbose_name='点踩该信息的用户'),
        ),
        migrations.AlterField(
            model_name='message',
            name='who_like',
            field=models.ManyToManyField(blank=True, related_name='message_who_like_set', to='WW.User', verbose_name='点赞该信息的用户'),
        ),
    ]
