# Generated by Django 2.1.7 on 2020-04-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0036_auto_20200409_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('universal', 'Universal'), ('avatar', 'Avatar')], default='universal', max_length=31, verbose_name='图片类型'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=62, null=True, verbose_name='信息标题'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='unknown', max_length=31, verbose_name='性别'),
        ),
    ]
