# Generated by Django 2.1.7 on 2020-04-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0037_auto_20200409_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='device',
            field=models.TextField(blank=True, verbose_name='设备信息'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('parent', 'Parent'), ('child', 'Child')], default='parent', max_length=31, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('universal', 'Universal'), ('avatar', 'Avatar'), ('unknown', 'Unknown')], default='universal', max_length=31, verbose_name='图片类型'),
        ),
    ]
