# Generated by Django 2.1.7 on 2020-04-16 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0038_auto_20200413_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='信息视频唯一标识符')),
                ('video', models.CharField(max_length=500, verbose_name='存储视频地址')),
                ('deleted', models.IntegerField(default=0, verbose_name='是否被删除')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW.Message', verbose_name='该图片所属信息')),
            ],
            options={
                'verbose_name': 'MessageVideo',
                'verbose_name_plural': 'MessageVideos',
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('child', 'Child'), ('parent', 'Parent')], default='parent', max_length=31, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('universal', 'Universal'), ('unknown', 'Unknown'), ('avatar', 'Avatar')], default='universal', max_length=31, verbose_name='图片类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='unknown', max_length=31, verbose_name='性别'),
        ),
    ]
