# Generated by Django 2.1.7 on 2020-04-16 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0039_auto_20200416_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='设备信息唯一标识符')),
                ('phone_model', models.CharField(max_length=63, verbose_name='手机型号')),
                ('imei', models.CharField(max_length=31, verbose_name='IMEI')),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdevice_device_set', to='WW.Device', verbose_name='用户')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('parent', 'Parent'), ('child', 'Child')], default='parent', max_length=31, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('avatar', 'Avatar'), ('universal', 'Universal')], default='universal', max_length=31, verbose_name='图片类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='unknown', max_length=31, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdevice_user_set', to='WW.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='user',
            name='devices',
            field=models.ManyToManyField(related_name='device_set', through='WW.UserDevice', to='WW.Device', verbose_name='使用过的设备'),
        ),
    ]
