# Generated by Django 2.1.7 on 2020-04-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0040_auto_20200416_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('child', 'Child'), ('parent', 'Parent')], default='parent', max_length=31, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('universal', 'Universal'), ('unknown', 'Unknown'), ('avatar', 'Avatar')], default='universal', max_length=31, verbose_name='图片类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='unknown', max_length=31, verbose_name='性别'),
        ),
    ]
