# Generated by Django 2.1.7 on 2020-04-30 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0041_auto_20200416_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='版本号唯一标识符')),
                ('version', models.CharField(max_length=62, verbose_name='版本号')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='该版本号发布的日期')),
            ],
        ),
    ]
