# Generated by Django 2.1.7 on 2020-05-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0042_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='description',
            field=models.TextField(default='最新的版本', verbose_name='版本描述'),
        ),
        migrations.AddField(
            model_name='version',
            name='download_link',
            field=models.CharField(default='media/documents/0.1.apk', max_length=242, verbose_name='下载地址'),
        ),
    ]
