# Generated by Django 2.1.7 on 2020-06-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0043_auto_20200511_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tested',
            field=models.BooleanField(default=False, verbose_name='是否已检测'),
        ),
        migrations.AddField(
            model_name='image',
            name='tested',
            field=models.BooleanField(default=False, verbose_name='是否已检测'),
        ),
        migrations.AddField(
            model_name='message',
            name='tested',
            field=models.BooleanField(default=False, verbose_name='是否已检测'),
        ),
        migrations.AddField(
            model_name='video',
            name='tested',
            field=models.BooleanField(default=False, verbose_name='是否已检测'),
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('universal', 'Universal'), ('avatar', 'Avatar'), ('unknown', 'Unknown')], default='universal', max_length=31, verbose_name='图片类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='unknown', max_length=31, verbose_name='性别'),
        ),
    ]
