# Generated by Django 2.1.7 on 2020-06-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0044_auto_20200604_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='conclusionType',
            field=models.CharField(max_length=10, null=True, verbose_name='检测结果'),
        ),
        migrations.AddField(
            model_name='image',
            name='conclusionType',
            field=models.CharField(max_length=10, null=True, verbose_name='检测结果'),
        ),
        migrations.AddField(
            model_name='message',
            name='conclusionType',
            field=models.CharField(max_length=10, null=True, verbose_name='检测结果'),
        ),
        migrations.AddField(
            model_name='video',
            name='conclusionType',
            field=models.CharField(max_length=10, null=True, verbose_name='检测结果'),
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('avatar', 'Avatar'), ('unknown', 'Unknown'), ('universal', 'Universal')], default='universal', max_length=31, verbose_name='图片类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='unknown', max_length=31, verbose_name='性别'),
        ),
    ]
