# Generated by Django 2.1.4 on 2020-02-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0010_user_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='deleted',
            field=models.IntegerField(default=0, verbose_name='是否被删除'),
        ),
        migrations.AddField(
            model_name='commentimage',
            name='deleted',
            field=models.IntegerField(default=0, verbose_name='是否被删除'),
        ),
        migrations.AddField(
            model_name='followship',
            name='deleted',
            field=models.IntegerField(default=0, verbose_name='是否被删除'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='deleted',
            field=models.IntegerField(default=0, verbose_name='是否被删除'),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted',
            field=models.IntegerField(default=0, verbose_name='是否被删除'),
        ),
        migrations.AddField(
            model_name='messageimage',
            name='deleted',
            field=models.IntegerField(default=0, verbose_name='是否被删除'),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.IntegerField(default=0, verbose_name='是否被删除'),
        ),
    ]
