# Generated by Django 2.1.7 on 2020-03-04 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0011_auto_20200227_1958'),
        ('WW', '0011_auto_20200227_1349'),
    ]

    operations = [
    ]
